<a href="https://colab.research.google.com/github/updalla-apshir/machine-learning-projects/blob/main/4_9_Numerical_Dataset_Pre_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
diabetes_data = pd.read_csv('/content/diabetes.csv')

In [ ]:
diabetes_data

     Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
diabetes_data.shape

(768, 9)

In [ ]:
diabetes_data.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

## Separating features and target

In [ ]:
# X = diabetes_data.drop('Outcome',axis=1)
# not need axis
X = diabetes_data.drop(columns='Outcome')
Y = diabetes_data['Outcome']

In [ ]:
print(X)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [ ]:
X.shape

(768, 8)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
print(X.shape,x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)

In [ ]:
print(Y.shape, y_train.shape, y_test.shape)

(768,) (614,) (154,)

In [ ]:
print(X.std().sum(), x_train.std().sum(), x_test.std().sum())

205.8699438036128 211.40366941068285 177.7969529897996

In [ ]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
print(x)

[[ 1.26486217  1.6953425   1.06962113 ...  0.20871544 -0.02463589
   2.08994783]
 [-1.14795452  1.82071923 -0.16197263 ...  1.25644556  4.11951333
  -0.69692436]
 [ 1.86806635  0.53560775  0.55645706 ... -0.62441936  2.80594009
   2.00549716]
 ...
 [ 0.36005591 -1.53310828 -0.46987107 ... -0.66228912 -0.60295685
  -0.52802301]
 [-0.24314826 -0.34202935  1.06962113 ... -0.46031705  0.05673591
  -0.35912167]
 [-1.14795452  0.47291939 -0.05933982 ... -0.91475421 -0.96622379
  -1.03472705]]

In [ ]:
print(x_train.std().sum())

1.0

In [ ]:
x_test = scaler.transform(x_test)
print(x_test.std().sum())

0.9485175412689734

In [ ]:
print(x_test)

[[ 0.96326009  0.44157521  0.24855862 ... -0.76327516  0.4984685
   1.49879312]
 [-0.54475035 -0.4360619  -0.88040233 ...  0.05723639 -0.45765008
  -0.95027638]
 [ 0.661658   -0.74950372 -0.57250389 ...  0.2465852  -0.1321629
   0.82318774]
 ...
 [-0.24314826 -1.313699    0.65908988 ...  0.27183171  2.3729259
  -0.52802301]
 [-0.84635244 -0.84353627 -0.16197263 ... -1.57116344 -0.41115191
  -0.69692436]
 [ 1.86806635 -0.4360619  -0.16197263 ...  0.04461313 -0.59133231
   0.73873707]]