<a href="https://colab.research.google.com/github/updalla-apshir/machine-learning-projects/blob/main/Project_1_Rock_vs_Mine_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the Dependencies

In [ ]:
import numpy as np
import pandas as pd
# from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.datasets import fetch_openml

loading the dataset

In [ ]:
sonar = fetch_openml(name='sonar',version=1,as_frame=True)

In [ ]:
X = sonar.data
Y = sonar.target

In [ ]:
X

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_51,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0203,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0051,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0155,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0042,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0181,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115

In [ ]:
# number of rows and columns
X.shape

(208, 60)

In [ ]:
# get statistical measures of the data
X.describe()

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_51,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [ ]:
# checking the values of each
Y.value_counts()

Class
Mine    111
Rock     97
Name: count, dtype: int64

In [ ]:
# get the mean of each of the 60 features.
X.groupby(Y).mean()

/tmp/ipykernel_1456/1614939138.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  X.groupby(Y).mean()

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_51,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60
Class,,,,,,,,,,,,,,,,,,,,,
Mine,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
Rock,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

Spliting the data into training and tes data

In [ ]:
x_train, x_test , y_train, y_test = train_test_split(X,Y, test_size=0.1, stratify=Y,random_state=1)

In [ ]:
print(X.shape,x_train.shape,x_test.shape)

(208, 60) (187, 60) (21, 60)

In [ ]:
print(Y.shape,y_train.shape,y_test.shape)

(208,) (187,) (21,)

Model Training -> Logistic Regression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
## Model Evaluation
train_prediction = model.predict(x_train)
train_prediction_accuracy = accuracy_score(y_train, train_prediction)

In [ ]:
print('Accuracy training data: ',train_prediction_accuracy)

Accuracy training data:  0.8342245989304813

In [ ]:
test_prediction = model.predict(x_test)
test_prediction_accuracy = accuracy_score(test_prediction,y_test)

In [ ]:
print('Accuracy testing data: ',test_prediction_accuracy)

Accuracy testing data:  0.7619047619047619

## Making a Predictive System

In [ ]:
input = (0.0164, 0.0173, 0.0347, 0.007, 0.0187, 0.0671, 0.1056, 0.0697, 0.0962, 0.0251, 0.0801, 0.1056, 0.1266, 0.089, 0.0198, 0.1133, 0.2826, 0.3234, 0.3238, 0.4333, 0.6068, 0.7652, 0.9203, 0.9719, 0.9207, 0.7545, 0.8289, 0.8907, 0.7309, 0.6896, 0.5829, 0.4935, 0.3101, 0.0306, 0.0244, 0.1108, 0.1594, 0.1371, 0.0696, 0.0452, 0.062, 0.1421, 0.1597, 0.1384, 0.0372, 0.0688, 0.0867, 0.0513, 0.0092, 0.0198, 0.0118, 0.009, 0.0223, 0.0179, 0.0084, 0.0068, 0.0032, 0.0035, 0.0056, 0.004
)
# changing the input data to a numpy array
input_as_array = np.asarray(input)

# reshape the np array as we predicting for one instance
input_data_reshaped = input_as_array.reshape(1,-1)


prediction = model.predict(input_data_reshaped)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
print(prediction)

['Rock']

Printing the SONAR Data

In [ ]:
sample = X.iloc[9].values

print(", ".join(map(str, sample)))

0.0164, 0.0173, 0.0347, 0.007, 0.0187, 0.0671, 0.1056, 0.0697, 0.0962, 0.0251, 0.0801, 0.1056, 0.1266, 0.089, 0.0198, 0.1133, 0.2826, 0.3234, 0.3238, 0.4333, 0.6068, 0.7652, 0.9203, 0.9719, 0.9207, 0.7545, 0.8289, 0.8907, 0.7309, 0.6896, 0.5829, 0.4935, 0.3101, 0.0306, 0.0244, 0.1108, 0.1594, 0.1371, 0.0696, 0.0452, 0.062, 0.1421, 0.1597, 0.1384, 0.0372, 0.0688, 0.0867, 0.0513, 0.0092, 0.0198, 0.0118, 0.009, 0.0223, 0.0179, 0.0084, 0.0068, 0.0032, 0.0035, 0.0056, 0.004

In [ ]:
Y[9]

'Rock'