<a href="https://colab.research.google.com/github/updalla-apshir/machine-learning-projects/blob/main/Project_2_Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.datasets import fetch_openml

In [ ]:
diabetes = fetch_openml(name='diabetes',as_frame=True)

/usr/local/lib/python3.12/dist-packages/sklearn/datasets/_openml.py:323: UserWarning: Multiple active versions of the dataset matching the name diabetes exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=37
- version 5, status: active
  url: https://www.openml.org/search?type=data&id=42608

  warn(warning_msg)

In [ ]:
X = diabetes.data
Y = diabetes.target

In [ ]:
X.shape

(768, 8)

getting the statictical measures of the data

In [ ]:

X.describe()

             preg        plas        pres  ...        mass        pedi         age
count  768.000000  768.000000  768.000000  ...  768.000000  768.000000  768.000000
mean     3.845052  120.894531   69.105469  ...   31.992578    0.471876   33.240885
std      3.369578   31.972618   19.355807  ...    7.884160    0.331329   11.760232
min      0.000000    0.000000    0.000000  ...    0.000000    0.078000   21.000000
25%      1.000000   99.000000   62.000000  ...   27.300000    0.243750   24.000000
50%      3.000000  117.000000   72.000000  ...   32.000000    0.372500   29.000000
75%      6.000000  140.250000   80.000000  ...   36.600000    0.626250   41.000000
max     17.000000  199.000000  122.000000  ...   67.100000    2.420000   81.000000

[8 rows x 8 columns]

In [ ]:
Y.value_counts()

class
tested_negative    500
tested_positive    268
Name: count, dtype: int64

In [ ]:
X.groupby(Y).mean()

/tmp/ipykernel_634/2650250950.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  X.groupby(Y).mean()

                     preg        plas  ...      pedi        age
class                                  ...
tested_negative  3.298000  109.980000  ...  0.429734  31.190000
tested_positive  4.865672  141.257463  ...  0.550500  37.067164

[2 rows x 8 columns]

Split into Training and Test data

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

Data Standardization

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit(x_train)

StandardScaler()

In [ ]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

Training the model

In [ ]:
classifier_model = svm.SVC(kernel='linear')

In [ ]:
# training the super vector machine classifier
classifier_model.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
train_prediction = classifier_model.predict(x_train)
test_prediction = classifier_model.predict(x_test)

Model Evaluation

In [ ]:
# the accuracy of the training model or evaluating the model
train_prediction_accuracy = accuracy_score(train_prediction,y_train)

In [ ]:
print('The Accuracy Score of training Data: ',train_prediction_accuracy)

The Accuracy Score of training Data:  0.7866449511400652

In [ ]:
# testing the accuracy of the test model or evaluating the model
test_prediction_accuracy = accuracy_score(test_prediction,y_test)

In [ ]:
print('The Accuracy Score of testing Data: ',test_prediction_accuracy)

The Accuracy Score of testing Data:  0.7727272727272727

## Making a Predictive System

In [ ]:
input = (1.0,95.0,74.0,21.0,73.0,25.9,0.673,36.0)


# changing the input data to a numpy array
input_as_array = np.asarray(input)

# reshape the np array
input_reshape = input_as_array.reshape(1,-1)

#standardize the input data
std_data = scaler.transform(input_reshape)

predict = classifier_model.predict(std_data)

if predict[0] == 'tested_positive':
  print('The person is diabetic')
else:
  print('The person is not diabetic')

The person is not diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
print(predict)

['tested_negative']

In [ ]:
# printing values we want to predict
values = X.iloc[341].values
print(','.join(map(str,values)))

1.0,95.0,74.0,21.0,73.0,25.9,0.673,36.0

In [ ]:
print(Y[341])

tested_negative